version: '3'

services:
  web:
    build: .
    image: django_docker
    command: python manage.py runserver 0:8000
    env_file: 
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - django_docker

networks:
  django_docker:

